// Generated by https://pagedraw.io/pages/5788
import React from 'react';
import './component_1.css';

function render() {
    return <div className="component_1">
        <div className="component_1-0">
            <div className="component_1-component_1">
                <div className="component_1-0-0-0">
                    <input type="text" placeholder="Id" className="component_1-text_input-6" /> 
                    <input type="text" placeholder="Decimals" className="component_1-text_input-67" /> 
                    <input type="text" placeholder="Min" className="component_1-text_input-9" /> 
                    <input type="text" placeholder="Max" className="component_1-text_input-3" /> 
                    <button type="submit" onClick={() => {this.props.deleteRow()}} className="component_1-button-6">
                        <span>X</span>
                    </button>
                </div>
                <div className="component_1-0-0-1">
                    <div className="component_1-text-0">Cannot be null</div>
                    <div className="component_1-text-8">Cannot be null</div>
                    <div className="component_1-text-6">Cannot be null</div>
                    <div className="component_1-text-4">Cannot be null</div>
                </div>
                <div className="component_1-0-0-2" /> 
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}