// Generated by https://pagedraw.io/pages/5788
import React from 'react';
import './rows.css';

function render() {
    return <div className="rows">
        <div className="rows-0">
            <div className="rows-rows-2">
                <div className="rows-0-0-0">
                    <div className="rows-text_2">Attributes:</div>
                </div>
                <div className="rows-0-0-1">
                    <div className="rows-0-0-1-0">
                        { this.props.rows.map((row, i) => {
                            return <div key={i} className="rows-rectangle-4">
                                <div className="rows-0-0-1-0-0-0-0">
                                    <input type="text" placeholder="Id" className="rows-text_input-5" /> 
                                    <input type="text" placeholder="Decimals" className="rows-text_input-1" /> 
                                    <input type="text" placeholder="Min" className="rows-text_input-0" /> 
                                    <input type="text" placeholder="Max" className="rows-text_input-9" /> 
                                    <button type="submit" onClick={() => {this.props.deleteRow()}} className="rows-button-4">
                                        <span>X</span>
                                    </button>
                                </div>
                                <div className="rows-0-0-1-0-0-0-1">
                                    <div className="rows-text-2">Cannot be null</div>
                                    <div className="rows-text-0">Cannot be null</div>
                                    <div className="rows-text-5">Cannot be null</div>
                                    <div className="rows-text-54">Cannot be null</div>
                                </div>
                            </div>;
                        }) }
                    </div>
                </div>
                <div className="rows-0-0-2">
                    <button type="submit" onClick={() => {this.props.addRow()}} className="rows-button-0">
                        <span>Add requirement</span>
                    </button>
                </div>
                <div className="rows-0-0-3" /> 
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}