// Generated by https://pagedraw.io/pages/5788
import React from 'react';
import './rowscomponent.css';

function render() {
    return <div className="rowscomponent">
        <div className="rowscomponent-0">
            <div className="rowscomponent-rowscomponent-2">
                <div className="rowscomponent-0-0-0">
                    <div className="rowscomponent-text_2">Attributes:</div>
                </div>
                <div className="rowscomponent-0-0-1">
                    <div className="rowscomponent-0-0-1-0">
                        { this.props.rows.map((row, i) => {
                            return <div key={i} className="rowscomponent-rectangle-4">
                                <div className="rowscomponent-0-0-1-0-0-0-0">
                                    <input type="text" placeholder="Id" value={row.id} onChange={this.props.onChangeId} onClick={()=>{this.props.onClickInput(i)}} className="rowscomponent-text_input-5" /> 
                                    <input type="text" placeholder="Decimals" value={row.decimals} className="rowscomponent-text_input-1" /> 
                                    <input type="text" placeholder="Min" value={row.min} className="rowscomponent-text_input-0" /> 
                                    <input type="text" placeholder="Max" value={row.max} className="rowscomponent-text_input-9" /> 
                                    <button type="submit" onClick={() => {this.props.deleteRow(i)}} className="rowscomponent-button-4">
                                        <span>X</span>
                                    </button>
                                </div>
                                <div className="rowscomponent-0-0-1-0-0-0-1">
                                    <div className="rowscomponent-text-2">Cannot be null</div>
                                    <div className="rowscomponent-text-0">Cannot be null</div>
                                    <div className="rowscomponent-text-5">Cannot be null</div>
                                    <div className="rowscomponent-text-54">Cannot be null</div>
                                </div>
                            </div>;
                        }) }
                    </div>
                </div>
                <div className="rowscomponent-0-0-2">
                    <button type="submit" onClick={() => {this.props.addRow()}} className="rowscomponent-button-0">
                        <span>Add requirement</span>
                    </button>
                </div>
                <div className="rowscomponent-0-0-3" /> 
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}